<?php namespace App\Libraries\CafeVariome\Core\IO\FileSystem;

/**
 * FileTest.php
 * Created 1/11/2022
 * @author Mehdi Mehtarizadeh
 */

use PHPUnit\Framework\TestCase;

/**
 * @covers \App\Libraries\CafeVariome\Core\IO\FileSystem\File
 */
class FileTest extends TestCase
{
	protected File $mockFile;
	protected string $tempPath;

	protected function setUp(): void
	{
		$this->tempPath = uniqid() . '/' . uniqid();
		$this->mockFile = new File(
			'test_file.php',
			1024,
			$this->tempPath,
			'php',
			0,
			true,
			32
		);
	}

	protected function tearDown(): void
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	public function testGetDiskName()
    {
		$this->assertNotEmpty($this->mockFile->getDiskName());
	}

    public function testGetTempPath()
    {
		$this->assertSame($this->tempPath, $this->mockFile->getTempPath());
    }

    public function testGetSize()
    {
		$this->assertEquals(1024, $this->mockFile->getSize());
    }

    public function testGetName()
    {
		$this->assertSame('test_file.php', $this->mockFile->getName());
    }

    public function testGetType()
    {
		$this->assertSame('php', $this->mockFile->getType());
	}

    public function testGetExtension()
    {
		$this->assertSame('php', $this->mockFile->getExtension());
		$mockNoExtensionFile = new File(
			'test_file',
			1024,
			$this->tempPath,
			'',
			0,
			true,
			32
		);
		$this->assertSame('', $mockNoExtensionFile->getExtension());
	}

	public function testFileProperties()
	{
		$name = 'test_file.txt';
		$size = 1024;
		$tempPath = '/tmp';
		$type = 'text/plain';
		$error = 0;

		$file = new File($name, $size, $tempPath, $type, $error);

		$this->assertEquals($name, $file->getName());
		$this->assertEquals('txt', $file->getExtension());
		$this->assertEquals($size, $file->getSize());
		$this->assertEquals($tempPath, $file->getTempPath());
		$this->assertEquals($type, $file->getType());

		$useDiskName = true;
		$diskNameLength = 32;
		$fileWithDiskName = new File($name, $size, $tempPath, $type, $error, $useDiskName, $diskNameLength);

		$this->assertNotEquals('', $fileWithDiskName->getDiskName());

		$pattern = '/^[0-9a-fA-F]+$/';
		$this->assertMatchesRegularExpression($pattern, pathinfo($fileWithDiskName->getDiskName(), PATHINFO_FILENAME));
	}
}
